Remove allocators from ntirpc_pkg_params
nfs-ganesha/ntirpc pull request #163
Opened 2019-01-17 04:41 UTC by malahal

Directly using malloc and friends should be better than having our own
functions to trace memory allocations using mtrace/muntrace etc.

Changed minor version to 8.

2019-01-17 04:44 UTC, malahal commented
I could keep the structure same and just don't use the passed in allocator/free functions, but I thought this is cleaner. I am assuming that we need [minor]version change here.

2019-01-17 13:29 UTC, dang commented
This needs discussion with Matt, who's traveling this week.

2019-03-13 12:47 UTC, mattbenjamin commented
the purpose of this wasn't to use tracing, but to ensure that we use the same allocator ganesha or another consumer does

2020-11-02 14:32 UTC, nuzhatfathima commented
@dang We would need this change to use for memory leak tracing which was reported recently. Can you please review this patch.

2020-11-02 15:19 UTC, mattbenjamin commented
@nuzhatfathima   I don't understand why you need this change to trace any way you want to

2024-05-14 20:10 UTC, ffilz requested changes
We want to leave the capability for Ganesha to provide allocators.

Rejecting.

2024-12-05 20:03 UTC, ffilz commented
This is quite old... Closing...

2024-12-05 20:03 UTC, closed without merging