[DRAFT] conversion and size fixes in xdr.h
nfs-ganesha/ntirpc pull request #228
Opened 2021-04-23 16:29 UTC by jobol

The first commit that adds explicit conversion is good to be taken IMHO

The 2 others, I don't know! I have no understanding of why using 32 bits in one direction and 16 in the other. My best bet is that getting would imply an intermediate memory for reading the real 32 bits and someone expected to be able to optimize the protocol.

So I push that proposal and expect some explanation that pull me from darkness.

2021-04-23 17:55 UTC, dang requested changes
This seems fine.  It makes no actual change to the on-wire data, since everything in XDR is transmitted as 32-bit unsigned integers, but it's more correct from a code perspective, and can remove compiler warnings.

Please remove DRAFT from the title, and sign all the commits.

2021-04-23 20:52 UTC, jobol commented
Hi @dang, I just removed DRAFT and signed  commits

2021-04-23 22:34 UTC, ffilz commented on ntirpc/rpc/xdr.h
> +	if (!xdr_getint32(xdrs, &lv))
This doesn't seem right, lv is uint32_t

2021-04-23 22:51 UTC, jobol commented on ntirpc/rpc/xdr.h
> +	if (!xdr_getint32(xdrs, &lv))
right, thanks hawkeyes

2021-04-23 22:51 UTC, jobol commented on ntirpc/rpc/xdr.h
> +	if (!xdr_getint32(xdrs, &lv))
pushed  the fix

2021-04-26 13:04 UTC, dang approved these changes

2021-10-15 07:51 UTC, jobol commented
ping

2021-10-15 14:44 UTC, dang commented
@ffilz ?

2021-10-15 20:58 UTC, ffilz commented
I think these are ready to go now. We should merge these and have an ntirpc pullup patch for nfs-ganesha

2021-10-18 14:56 UTC, merged