Getting rid of varargs
nfs-ganesha/ntirpc pull request #244
Opened 2021-10-28 15:59 UTC by Safrout1

Varargs create problems when running nfs-ganesha on M1 Macs, resulting in null pointers. Thus, this pull request eliminates the existence of varargs.

2021-10-28 23:18 UTC, matvore commented
You should squash the last two commits into one so this is easier to review and doesn't pollute the Git history with your generated cmake files.

Motivation for this PR: https://github.com/nfs-ganesha/ntirpc/issues/242
Precedent for this approach is in the macOS SDK (see Sept 17 comment in above issue)

2021-10-29 14:07 UTC, dang commented
I don't see how this is possible.  Varargs are a standard part of C, and have been for decades.  There must be some way to support varargs on M1 macs.

2021-10-29 14:17 UTC, dang requested changes
Okay, I see the issue, it's not actually using varargs.  Can you squash all the commits together (or remove the extraneous ones), and make sure the commit message explains that it was casting a pointer to a non-varargs function to a pointer to a varargs function?

2021-11-02 22:37 UTC, matvore commented on ntirpc/rpc/xdr.h
> +typedef bool(*xdrproc_t) (XDR *, void *, unsigned int);
u_int will always be unsigned int, as far as I know. You could just remove the `#ifdef` conditional and always use this typedef (i.e. spell out `unsigned int`)

2021-11-03 15:46 UTC, Safrout1 commented
> Okay, I see the issue, it's not actually using varargs. Can you squash all the commits together (or remove the extraneous ones), and make sure the commit message explains that it was casting a pointer to a non-varargs function to a pointer to a varargs function?

Sorry for the inconvenience, I created another pull request: https://github.com/nfs-ganesha/ntirpc/pull/245

2021-11-03 15:47 UTC, closed without merging