fixbug memory leak
nfs-ganesha/ntirpc pull request #271
Opened 2023-02-13 11:21 UTC by riweirui

2023-02-13 15:36 UTC, dang reviewed
Can you please update the commit message to explain the leak?  This code is standard refcounting code, and the change is an odd one.

2023-11-09 06:06 UTC, chengmao2010 commented
> Can you please update the commit message to explain the leak? This code is standard refcounting code, and the change is an odd one.

Uio reference not  increase after call XDR_PUTBYTES，so uio will never be freed

2023-11-09 15:52 UTC, ffilz requested changes
This also needs more commit message than "fixbug memory leak"

2023-11-09 15:52 UTC, ffilz commented on src/xdr_mem.c
> +    }
Please add a comment here explaining because otherwise that code looks really odd.

2023-11-09 15:52 UTC, ffilz commented on src/xdr_mem.c
> +		abort();
Please fix the indentation on this block

2024-05-14 19:54 UTC, ffilz commented
> > Can you please update the commit message to explain the leak? This code is standard refcounting code, and the change is an odd one.
> 
> Uio reference not increase after call XDR_PUTBYTES，so uio will never be freed

Should we actually make a change there?

2025-05-06 14:26 UTC, dang commented
No response.

2025-05-06 14:26 UTC, closed without merging