Don't free nonheap memory.
nfs-ganesha/ntirpc pull request #53
Opened 2017-06-13 16:03 UTC by sswen

Function inline_xdr_bytes might try to free
nonheap memory referenced by the cpp parameter.

Signed-off-by: Swen Schillig <swen@vnet.ibm.com>

2017-06-13 16:20 UTC, dang commented
When can non-allocated memory be freed?  The only things passed to XDR_FREE should be things gotten from XDR_DECODE, I believe.

2017-06-13 19:08 UTC, sswen commented
Actuallly, most calling functions do reserve the bufer memory themselves and a some do it on the stack which causes the issue mentioned.
E.g. xdr_encode_nfs4_princ()
Even if inline_xdr_bytes is allocating the memory, it is never referenced by any calling function after that and only used as a buffer for the task triggered at the time.

2017-06-13 19:17 UTC, sswen commented
If you find a place where the memory allocated by inline_xdr_bytes is used from the calling func we can assign it to *cpp, but I didn't see that. Regardless inline_xdr_bytes should never free memory unless we are 100% sure it got allocated from this func, which is currently not possible once the allocating context is left. Therefore, I would suggest to always free such memory by XDR_DESTROY.

2017-06-14 18:19 UTC, malahal commented
based on the loose code here, we can assume that the caller might allocate or not. It is generally assumed that the caller will NOT free if the callee returns an error.  So why not free (if we allocated here) when we return an error?

2017-06-16 06:28 UTC, sswen commented
Correct.
But the way I suggested is free'ing the code at the end automatically, regardless (->alloca).
...as I haven't seen the allocated memory being used by the caller anywhere.

2017-06-16 13:35 UTC, dang commented
So, I'm not sure this is necessary.  The pragma is that you free it and set it to NULL, or you ignore it and let inline_xdr_bytes() free it.  So, if a caller doesn't want it freed, they should set it to NULL.  This is very commonly done in Ganesha (see nfs4_Fattr_Free() for example).

What are the codepaths that were causing problems?  There are hundreds, and I haven't been able to find any yet.

2017-06-19 06:29 UTC, sswen commented
Ok, the issue popped up with XDR_DECODE and I just added the same handling to XDR_FREE, maybe that is the disagreement here.
As for XDR_DECODE I already gave an example where it doesn't work.
I could agree to your statement if we're just talking about XDR_FREE and would, therefore, re-introduce that code again.
Would that be OK for you ?

2017-06-19 06:54 UTC, malahal commented
[ 87%] Building C object idmapper/CMakeFiles/idmap.dir/idmapper.c.o
In file included from /home/malahal/nfs-ganesha/src/include/gsh_rpc.h:17:0,
                 from /home/malahal/nfs-ganesha/src/include/uid2grp.h:44,
                 from /home/malahal/nfs-ganesha/src/include/fsal_types.h:42,
                 from /home/malahal/nfs-ganesha/src/include/fsal_api.h:43,
                 from /home/malahal/nfs-ganesha/src/include/fsal.h:62,
                 from /home/malahal/nfs-ganesha/src/include/export_mgr.h:42,
                 from /home/malahal/nfs-ganesha/src/include/nfs_exports.h:48,
                 from /home/malahal/nfs-ganesha/src/idmapper/idmapper.c:47:
In function ‘inline_xdr_bytes.constprop.4’,
    inlined from ‘xdr_encode_nfs4_princ’ at /home/malahal/nfs-ganesha/src/idmapper/idmapper.c:119:3:
/home/malahal/nfs-ganesha/src/libntirpc/ntirpc/rpc/xdr_inline.h:609:8: warning: attempt to free a non-heap object ‘namebuf’ [-Wfree-nonheap-object]
    free(sp);
        ^
[ 88%] Building C object idmapper/CMakeFiles/idmap.dir/idmapper_cache.c.o

2017-06-20 15:53 UTC, malahal commented
We are allowing a decode caller with a null buffer and we decode here on the stack which the caller can't access. This interface is not expected to work.  We can as well remove this null buffer API in the decode path if no one is using now. If someone is using, it will not work after this fix. Am I missing something?

2017-06-20 16:46 UTC, dang commented
Okay, so this change won't work, and that codepath cannot hit (although the compiler likely can't tell).

First the change.  This is the decode path that's being changed, so it must return the value in *cpp.  This value must live beyond the call to inline_xdr_bytes(), so it must be allocated on the heap.   The codepaths I've followed in Ganesha (only a few, since they are horribly complicated to track down) all pre-allocate *cpp, so this is not an issue, but I believe the code in inline_xdr_bytes is correct as stands.

Now the warning.  xdr_encode_nfs4_princ() is fine, because it's calling an *encode*, which never hits the free path (which is part of *decode*).  Encode only reads from *cpp, never writes to it.

So, this change is wrong, and will break any caller that does not pre-allocate space for the decode.

2017-06-20 16:47 UTC, dang commented
We can't remove it, since this is a generic API intended to be used by other users than just Ganesha.

2017-06-20 17:29 UTC, malahal commented
The code path reported by the compiler can't be bit, but there is a bug here nonetheless. Assume a caller allocating stack buffer and then calling the DECODE path. If it fails, this code ends up freeing stack memory. Why not do what I suggested in my first comment? Here is the patch code (or something similar):
`diff --git a/ntirpc/rpc/xdr_inline.h b/ntirpc/rpc/xdr_inline.h
index 4e9a3f9..162408b 100644
--- a/ntirpc/rpc/xdr_inline.h
+++ b/ntirpc/rpc/xdr_inline.h
@@ -584,6 +584,7 @@ inline_xdr_bytes(XDR *xdrs, char **cpp, u_int *sizep,
        char *sp = *cpp;        /* sp is the actual string pointer */
        u_int nodesize;
        bool ret;
+       bool allocated = false;
 
        /*
         * first deal with the length since xdr bytes are counted
@@ -602,10 +603,12 @@ inline_xdr_bytes(XDR *xdrs, char **cpp, u_int *sizep,
        case XDR_DECODE:
                if (nodesize == 0)
                        return (true);
-               if (sp == NULL)
+               if (sp == NULL) {
                        *cpp = sp = (char *)mem_alloc(nodesize);
+                       allocated = true;
+               }
                ret = inline_xdr_getopaque(xdrs, sp, nodesize);
-               if (! ret) {
+               if (! ret && allocated) {
                        free(sp);
                        *cpp = NULL;
                }
`

2017-06-20 17:36 UTC, dang commented
That should work, I believe.

2017-06-20 17:45 UTC, ffilz commented
Yea, that is what some of the other functions have done. I was looking at this when we thought the security update patch to libntirpc was at fault.

Check the inline string function also...

2017-06-29 11:30 UTC, was4 commented
On 6/20/17 1:29 PM, Malahal wrote:
> The code path reported by the compiler can't be bit, but there is a bug here nonetheless. Assume a caller allocating stack buffer and then calling the DECODE path. If it fails, this code ends up freeing stack memory. Why not do what I suggested in my first 
> comment? Here is the patch code (or something similar):
> `diff --git a/ntirpc/rpc/xdr_inline.h b/ntirpc/rpc/xdr_inline.h
> index 4e9a3f9..162408b 100644
> --- a/ntirpc/rpc/xdr_inline.h
> +++ b/ntirpc/rpc/xdr_inline.h
> @@ -584,6 +584,7 @@ inline_xdr_bytes(XDR *xdrs, char **cpp, u_int *sizep,
> char *sp = /cpp; // sp is the actual string pointer */
> u_int nodesize;
> bool ret;
> 
>   *
> 
>     |bool allocated = false; /* * first deal with the length since xdr bytes are counted |
> 
> @@ -602,10 +603,12 @@ inline_xdr_bytes(XDR *xdrs, char **cpp, u_int *sizep,
> case XDR_DECODE:
> if (nodesize == 0)
> return (true);
> 
>   *
> 
>     |if (sp == NULL) |
> 
>   *
> 
>     |if (sp == NULL) { *cpp = sp = (char *)mem_alloc(nodesize); |
> 
>   *
> 
>     |allocated = true; |
> 
>   *
> 
>     |} ret = inline_xdr_getopaque(xdrs, sp, nodesize); |
> 
>   *
> 
>     |if (! ret) { |
> 
>   *
> 
>     |if (! ret && allocated) { free(sp); *cpp = NULL; } |
> 
>
I disagree with this code.  We don't need a separate allocated bool,
because the code that calls this always knows whether or not it has
allocated it.

If it has allocated it, then inline_xdr_getopaque() is called.

If it needs the malloc, then inline_xdr_bytes() is called.

Very simple and comprehensive interface.  We don't need to muck it up
with "meta" functions.

2017-06-29 11:35 UTC, was4 requested changes
This is a bad idea. If you know that you have already allocated the buffer, then inline_xdr_getopaque() should always be called directly.

Simple, clean interface. No meta functions needed.

-1

2017-06-29 11:46 UTC, malahal commented
>> If it needs the malloc, then inline_xdr_bytes() is called.

If this is indeed the case, why is cpp argument used as IN and OUT parameter. inline_xdr_bytes() should NOT look at passed in *cpp, just allocate if needed.

2017-06-30 08:23 UTC, sswen commented
Malahal, Bill
Thanks for your comments, but could you please have a look at the updated fix suggestion I posted a few days ago ?
The way I understood both of your comments, I believe the content of the current PR is doing what's wanted.

2018-08-02 14:49 UTC, dang commented
This code is very different on next.  I've opened a for that here: https://github.com/nfs-ganesha/ntirpc/pull/140

2018-08-07 17:40 UTC, dang commented
Fixed in pull #140

2018-08-07 17:40 UTC, closed without merging