Close in destroy_task(s)
nfs-ganesha/ntirpc pull request #80
Opened 2017-09-28 15:23 UTC by was4

Move closing the fd into the destroy_task(s) where we are reasonably sure
any outstanding poll for that fd has had the opportunity to terminate.

Signed-off-by: William Allen Simpson <william.allen.simpson@redhat.com>

2017-09-28 17:21 UTC, dang requested changes
This looks like a reasonable change, possibly closing a hole.  One minor nit.

2017-09-28 17:21 UTC, dang commented on src/svc_dg.c
> +		(void)close(rec->xprt.xp_fd);
This should probably set xp_fd to -1, just to close any other possible races on it.

2017-09-28 17:21 UTC, dang commented on src/svc_vc.c
> +		(void)close(rec->xprt.xp_fd);
Ditto here (and both places should probably use the same constant, either -1 or RPC_ANYFD)

2017-09-29 13:33 UTC, was4 commented
On 9/28/17 1:21 PM, Daniel Gryniewicz wrote:
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> In src/svc_dg.c <https://github.com/nfs-ganesha/ntirpc/pull/80#discussion_r141681994>:
> This should probably set xp_fd to -1, just to close any other possible races on it.
> 
There shouldn't be any races; because of the IOQ_FLAG_WORKING bit,
there can be only one.  But I suppose it cannot hurt.

> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> In src/svc_vc.c <https://github.com/nfs-ganesha/ntirpc/pull/80#discussion_r141682265>:
> Ditto here (and both places should probably use the same constant, either -1 or RPC_ANYFD)
> 
Code was simply moved; constants are in prior code.

ntirpc/rpc/svc.h:#define RPC_ANYSOCK -1
ntirpc/rpc/svc.h:#define RPC_ANYFD RPC_ANYSOCK

But I suppose it cannot hurt....

2017-10-02 12:49 UTC, dang approved these changes

2017-10-02 12:51 UTC, merged